location = /static/branding/logo.png {
    alias /config/branding/logo.png;
}

location = /static/branding/favicon.png {
    alias /config/branding/favicon.png;
}

location = /images/favicon.ico {
    alias /config/branding/favicon.png;
}

location = /images/favicon.svg {
    alias /config/branding/favicon.png;
}

location = /favicon.ico {
    alias /config/branding/favicon.png;
}

location = /title.html {
    alias /config/title.html;
}

location = /head.html {
    alias /config/head.html;
}

location = /lang/main-es.json {
    alias /config/lang/main-es.json;
}

location = /lang/main.json {
    alias /config/lang/main.json;
}

location = /lang/main-en.json {
    alias /config/lang/main.json;
}
